name: Sync Repositories
on:
  workflow_call:
    inputs:
      source-repo:
        description: "The full name (org/repo) of the source repository to sync from"
        required: false
        type: string
        default: "None"
      source-branch:
        description: "The branch name in the source repository to sync from"
        required: false
        type: string
        default: "main"
      destination-repo:
        description: "The full name (org/repo) of the destination repository to sync to"
        required: false
        type: string
        default: "None"
      destination-branch:
        description: "The branch name in the destination repository to sync to"
        required: false
        type: string
        default: "main"
      sync-operation:
        description: "The type of sync operation to perform (pull request or force push)"
        required: false
        type: string
        default: "pull_request"

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    permissions:
      contents: read
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      REPO_SYNC_GITHUB_APP_ID: ${{ secrets.REPO_SYNC_GITHUB_APP_ID }}
      REPO_SYNC_GITHUB_APP_PRIVATE_KEY: ${{ secrets.REPO_SYNC_GITHUB_APP_PRIVATE_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          fetch-depth: 0

      - name: Generate Repo Sync Workflow Token
        id: repo-sync-generate-token
        uses: actions/create-github-app-token@6c406e8a244fdf6bbf79e6cc8a91504a48d2c2ce
        with:
          app-id: ${{ env.REPO_SYNC_GITHUB_APP_ID }}
          private-key: ${{ env.REPO_SYNC_GITHUB_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Set up Git
        uses: wei/git-sync@v3
        with:
          source_repo: "https://x-access-token:${{steps.repo-sync-generate-token.outputs.token}}@github.com/GitSenku/DevPiece.git"
          source_branch: "main"
          destination_repo: "https://x-access-token:${{steps.repo-sync-generate-token.outputs.token}}@github.com/GitSenku/StoneScript.git"
          destination_branch: "feature/test"
